# Dev profile configuration

# Database Configuration for PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coople_scheduler_api
    username: superUser
    password: superUser
    driver-class-name: org.postgresql.Driver

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.coople.gamepartnerservice: INFO

# Server Configuration
server:
  port: 8085
